# Site settings
title: 激光82共享空间

github_username: jiguang82
permalink: /:year/:month/:day/:title/
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: jiguang82
disqus_url: "http://jiguang82.github.io"
#########################################

# Build settings
markdown: kramdown

