# Site settings
title: 激光82共享空间

github_username: jiguang82
permalink: /:year/:month/:day/:title/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/jiguang82/jiguang82/new/master

# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
duoshuo_shortname: jiguang82
duoshuo_url: "http://jiguang82.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: jiguang82
#disqus_url: "http://jiguang82.github.io"

#########################################

# Build settings
markdown: kramdown

